title = "Example plain_weather configuration file"

[api]
key = "Put your key here."

[location]
# Options ordered in terms of what will get used. Higher options override
# those below them.
# Latitude and longitude
lat = 0
long = 0
# Country code (used for rest of options)
country = "US"
# Zip code
zip = "99999"
# State code (only for the U.S.)
state = "DC"
# City
city = "Washington"